const teams = [
  {
    name: "Arizona Cardinals",
    imgSrc: "/Cardinals.png",
    city: "Phoenix, Arizona",
    description: "Rise Up Red Sea",
  },
  {
    name: "Atlanta Falcons",
    imgSrc: "/Falcons.png",
    city: "Atlanta, Georgia",
    description: "Rise Up",
  },
  {
    name: "Baltimore Ravens",
    imgSrc: "/Ravens.png",
    city: "Baltimore, Maryland",
    description: "Play Like A Raven",
  },
  {
    name: "Buffalo Bills",
    imgSrc: "/Bills.png",
    city: "Buffalo, New York",
    description: "Bills Mafia",
  },
  {
    name: "Carolina Panthers",
    imgSrc: "/Panthers.png",
    city: "Charlotte, North Carolina",
    description: "Keep Pounding",
  },
  {
    name: "Chicago Bears",
    imgSrc: "/Bears.png",
    city: "Chicago, Illinois",
    description: "Bear Down",
  },
  {
    name: "Cincinnati Bengals",
    imgSrc: "/Bengals.png",
    city: "Cincinnati, Ohio",
    description: "Who Dey",
  },
  {
    name: "Cleveland Browns",
    imgSrc: "/Browns.png",
    city: "Cleveland, Ohio",
    description: "Dawg Pound",
  },
  {
    name: "Dallas Cowboys",
    imgSrc: "/Cowboys.png",
    city: "Arlington, Texas",
    description: "America's Team",
  },
  {
    name: "Denver Broncos",
    imgSrc: "/Broncos.png",
    city: "Denver, Colorado",
    description: "Broncos Country",
  },
  {
    name: "Detroit Lions",
    imgSrc: "/Lions.png",
    city: "Detroit, Michigan",
    description: "One Pride",
  },
  {
    name: "Green Bay Packers",
    imgSrc: "/Packers.png",
    city: "Green Bay, Wisconsin",
    description: "Go Pack Go",
  },
  {
    name: "Houston Texans",
    imgSrc: "/Texans.png",
    city: "Houston, Texas",
    description: "We Are Texans",
  },
  {
    name: "Indianapolis Colts",
    imgSrc: "/Colts.png",
    city: "Indianapolis, Indiana",
    description: "For The Shoe",
  },
  {
    name: "Jacksonville Jaguars",
    imgSrc: "/Jaguars.png",
    city: "Jacksonville, Florida",
    description: "Duuuval",
  },
  {
    name: "Kansas City Chiefs",
    imgSrc: "/Chiefs.png",
    city: "Kansas City, Missouri",
    description: "Chiefs Kingdom",
  },
  {
    name: "Las Vegas Raiders",
    imgSrc: "/Raiders.png",
    city: "Las Vegas, Nevada",
    description: "Just Win Baby",
  },
  {
    name: "Los Angeles Chargers",
    imgSrc: "/Chargers.png",
    city: "Los Angeles, California",
    description: "Bolt Up",
  },
  {
    name: "Los Angeles Rams",
    imgSrc: "/Rams.png",
    city: "Los Angeles, California",
    description: "Rams House",
  },
  {
    name: "Miami Dolphins",
    imgSrc: "/Dolphins.png",
    city: "Miami, Florida",
    description: "Fins Up",
  },
  {
    name: "Minnesota Vikings",
    imgSrc: "/Vikings.png",
    city: "Minneapolis, Minnesota",
    description: "Skol",
  },
  {
    name: "New England Patriots",
    imgSrc: "/Patriots.png",
    city: "Foxborough, Massachusetts",
    description: "Do Your Job",
  },
  {
    name: "New Orleans Saints",
    imgSrc: "/Saints.png",
    city: "New Orleans, Louisiana",
    description: "Who Dat",
  },
  {
    name: "New York Giants",
    imgSrc: "/Giants.png",
    city: "East Rutherford, New Jersey",
    description: "Big Blue",
  },
  {
    name: "New York Jets",
    imgSrc: "/Jets.png",
    city: "East Rutherford, New Jersey",
    description: "Gang Green",
  },
  {
    name: "Philadelphia Eagles",
    imgSrc: "/Eagles.png",
    city: "Philadelphia, Pennsylvania",
    description: "Fly Eagles Fly",
  },
  {
    name: "Pittsburgh Steelers",
    imgSrc: "/Steelers.png",
    city: "Pittsburgh, Pennsylvania",
    description: "Here We Go",
  },
  {
    name: "San Francisco 49ers",
    imgSrc: "/49ers.png",
    city: "Santa Clara, California",
    description: "Faithful",
  },
  {
    name: "Seattle Seahawks",
    imgSrc: "/Seahawks.png",
    city: "Seattle, Washington",
    description: "Go Hawks",
  },
  {
    name: "Tampa Bay Buccaneers",
    imgSrc: "/Buccaneers.png",
    city: "Tampa, Florida",
    description: "Fire The Cannons",
  },
  {
    name: "Tennessee Titans",
    imgSrc: "/Titans.png",
    city: "Nashville, Tennessee",
    description: "Titan Up",
  },
  {
    name: "Washington Commanders",
    imgSrc: "/Commanders.png",
    city: "Landover, Maryland",
    description: "HTTC",
  },
];

export default teams;
